import { Injectable } from '@angular/core';
import { Item } from '../../features/inventory/models/item';

@Injectable({
  providedIn: 'root',
})
export class Items {
  list: Item[] = [
    {
      title: 'En-cas',
      description: 'Récupérez immédiatement 3 PV.',
      img_url: './sprites/en-cas.png',
      price: 3,
      chance_of_appearing: 90,
      interaction: {
        heroHeal: true,
        health: 3,
      },
      bought: false,
      directEffect: true,
    },
    {
      title: 'Repas',
      description: 'Récupérez immédiatement 6 PV.',
      img_url: './sprites/repas.png',
      price: 6,
      chance_of_appearing: 50,
      interaction: {
        heroHeal: true,
        health: 6,
      },
      bought: false,
      directEffect: true,
    },
    {
      title: 'Festin',
      description: 'Récupérez immédiatement 9 PV.',
      img_url: './sprites/festin.png',
      price: 9,
      chance_of_appearing: 10,
      interaction: {
        heroHeal: true,
        health: 9,
      },
      bought: false,
      directEffect: true,
    },
    {
      title: "Élixir d'endurance",
      description: 'Augmentez de 1 votre limite de PV jusqu’à la fin du donjon.',
      img_url: './sprites/elixir-endurance.png',
      price: 8,
      chance_of_appearing: 80,
      interaction: {
        endurance: true,
      },
      bought: false,
      directEffect: true,
    },
    {
      title: 'Parieur',
      description: 'Lancez immédiatement le dé : sur 4+, gagnez 20 pièces.',
      img_url: './sprites/parieur.png',
      price: 16,
      chance_of_appearing: 50,
      interaction: {},
      bought: false,
      directEffect: true,
    },
    {
      title: 'Crésus',
      description: 'Au prochain étage, doublez les pièces et les trésors gagnés.',
      img_url: './sprites/cresus.png',
      price: 20,
      chance_of_appearing: 40,
      interaction: {},
      bought: false,
      directEffect: true,
    },
    {
      title: 'Gringalets',
      description: 'Au prochain étage, considérez que tous les ennemis ont 1 PV.',
      img_url: './sprites/gringalets.png',
      price: 10,
      chance_of_appearing: 30,
      interaction: {},
      bought: false,
      directEffect: true,
    },
    {
      title: 'Bouclier magique',
      description: 'Au prochain étage, les ennemis ne vous font perdre aucun PV. En avant !',
      img_url: './sprites/bouclier-magique.png',
      price: 12,
      chance_of_appearing: 20,
      interaction: {},
      bought: false,
      directEffect: true,
    },
    {
      title: 'Passe-muraille',
      description: 'Traversez un mur qui vous bloque le passage.',
      img_url: './sprites/passe-muraille.png',
      price: 15,
      chance_of_appearing: 20,
      interaction: {},
      bought: false,
      directEffect: false,
    },
    {
      title: 'Téléparchemin',
      description: "Téléportez-vous sur n'importe quelle case à cet étage.",
      img_url: './sprites/teleparchemin.png',
      price: 25,
      chance_of_appearing: 10,
      interaction: {},
      bought: false,
      directEffect: false,
    },
    {
      title: 'Parchemulligan',
      description: 'Relancez une fois le dé.',
      img_url: './sprites/parchemulligan.png',
      price: 18,
      chance_of_appearing: 30,
      interaction: {},
      bought: false,
      directEffect: false,
    },
    {
      title: 'Doublélixir',
      description: 'Doublez le résultat du dé.',
      img_url: './sprites/doublelixir.png',
      price: 20,
      chance_of_appearing: 30,
      interaction: {},
      bought: false,
      directEffect: false,
    },
  ];
}
